### ISSUE TITLE
Best upgrade the used nodejs to v18

### ISSUE THREAD

**Issue by OfekShilon** [madduci/docker-compiler-explorer#10]
CE still agrees to run over v16 - but complains. It is [tested only on v18](https://github.com/compiler-explorer/compiler-explorer/blob/2dc89dde3bda4f066050de3bf0514906f02097c1/etc/scripts/find-node#L27)

I'm currently unable to make a PR, but it is a single character change:
https://github.com/madduci/docker-compiler-explorer/commit/c85e3cef242c80f3e00126055ef9afe70c6b6141

**Comment by madduci** [comment]
Hi @OfekShilon 

thanks for reporting it. I don't actively use the image myself anymore, so i was a bit out-of-date on the latest stand.
I'm made the suggested change, many thanks!
