### ISSUE TITLE
Short link return localhost not domain.

### ISSUE THREAD

**Issue by k0lo86** [madduci/docker-compiler-explorer#4]
Hi,

I use this container behind apache proxy in domain e.g. godbolt.example.com.
Short link option generate link: "http://localhost:10240/z/caM764"

How fix this?

**Comment by madduci** [comment]
Hi @kolos666 

thanks for opening a ticket. It looks like a specific proxy configuration issue and seems out of scope of this project, but related to how Compiler Explorer works.

By looking at the [original source code](https://github.com/compiler-explorer/compiler-explorer/blob/a6eef1356243241ac1cfaa69733511b835aea097/static/sharing.js#L102), the share Link functionality uses the `windows.location.origin`, which in your case might be wrong, in case you don't set the specific header.

Without knowing your proxy setup / configuration, I would suggest to set the "hostname" value in the docker-compose.yml file and define it as

`hostname: godboldt.example.com`

and set as proxy pass the correct headers.
I hope it helps.
